### ISSUE TITLE
Pull access denied even when logged into docker hub

### ISSUE THREAD

**Issue by pierskarsenbarg** [docker/doodle#3]
Ran `docker run it --rm surprise` as suggested. Received following error message:

```
Unable to find image 'surprise:latest' locally
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: pull access denied for surprise, repository does not exist or may require 'docker login'.
```

Logged into docker hub using `docker login`. Got same response again.

**Comment by pdevine** [comment]
@pierskarsenbarg I don't have a Windows machine to test this out on.  Is this still a problem?

**Comment by pdevine** [comment]
Going to close this as it seems to be working correctly.
