### ISSUE TITLE
Error when run build command.

### ISSUE THREAD

**Issue by evstpetr** [docker/doodle#4]
I ran command `'docker build -t evst ./'`
Building started successfuly but when it's almost done I faced with that error messages:

```
package golang.org/x/text/encoding: unrecognized import path "golang.org/x/text/encoding" (https fetch: Get https://golang.org/x/text/encoding?go-get=1: x509: certificate signed by unknown authority)
package golang.org/x/text/transform: unrecognized import path "golang.org/x/text/transform" (https fetch: Get https://golang.org/x/text/transform?go-get=1: x509: certificate signed by unknown authority)
```

Could you provide some tips, what should I do?

OS: Win 10.

**Comment by pdevine** [comment]
@evstpetr could you include the full logs?  I'm wondering if the Alpine `ca-certificates` image is somehow out of date.

**Comment by evstpetr** [comment]
I hope it helps.
`Sending build context to Docker daemon  14.34kB

Step 1/9 : FROM golang:1.11-alpine AS builder
 ---> 64ba145fa582

Step 2/9 : RUN apk add --no-cache git
 ---> Using cache
 ---> 493f51b1d6e0
Step 3/9 : RUN go get github.com/pdevine/go-asciisprite
 ---> Running in ff180cd95977
package golang.org/x/text/encoding: unrecognized import path "golang.org/x/text/encoding" (https fetch: Get https://golang.org/x/text/encoding?go-get=1: x509: certificate signed by unknown authority)
package golang.org/x/text/transform: unrecognized import path "golang.org/x/text/transform" (https fetch: Get https://golang.org/x/text/transform?go-get=1: x509: certificate signed by unknown authority)
The command '/bin/sh -c go get github.com/pdevine/go-asciisprite' returned a non-zero code: 1`

**Comment by pdevine** [comment]
Hmm.  I'm really not sure here.  I'm having a hard time reproducing the problem.  I have the same `golang:1.11-alpine` image that you have but it works fine in Linux as well as with Docker Desktop in OSX.

Can you try `docker build --no-cache -t evst ./` ?  I'm wondering whether `git` was installed incorrectly?

**Comment by evstpetr** [comment]
Unfortunately it did not help :( Also I changed `RUN go get -v -insecure github.com/pdevine/go-asciisprite`
After that I got another issue with ssl: 
`Cloning into '/go/src/golang.org/x/text'...
fatal: unable to access 'https://go.googlesource.com/text/': SSL certificate problem: unable to get local issuer certificate`
Also I've tried change version of base layer) `FROM golang:1.12.5-alpine3.9 AS builder`, it also didn't help.

**Comment by pdevine** [comment]
@evstpetr Which version of Docker are you using?  I'll see if I can get my hands on a Windows 10 machine.

**Comment by evstpetr** [comment]
`Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false`

**Comment by evstpetr** [comment]
I investigaed about it a bit more and found that I can't do `git clone https://go.googlesource.com/text /go/src/golang.org/x/text`, because of same problem with certificate. Sorry for spending your time :(

**Comment by pdevine** [comment]
@evstpetr did you figure out what the fix was for your host?  Just curious as other people may run across this.

**Comment by evstpetr** [comment]
@pdevine It's really strange. Today morning I came to the job, tried run building againt and wathed this:
`Successfully built 48249db435e1
Successfully tagged evst/cheers2019:latest`
I don't know why exactly everything fine now :( But I could suggest that our middleware staff add googlesource.com  to the 'white' list of permited addresses.

**Comment by pdevine** [comment]
Glad you got it working!

**Comment by Yeggy** [comment]
@pdevine I had the same problem today. I am running MacOS **10.14** and GO Lang version 1.13. I found two issues with the Dockerfile for the package that was causing this. GIT needs to be disabled for SSL verification and if GO Language is already installed, then GOPATH needs to be exported to the new shell that will do **"go get"**. Following are the statements in my Dockerfile inserted before the RUN command that made the error to go away. Hope this helps.

ENV GIT_SSL_NO_VERIFY=true
ENV GOPATH="GOPATH value set in your shell if GOLang is installed"

But I am having issues in pushing the image to my public repository in Docker Hub and debugging this.
