### ISSUE TITLE
 build error and maybe no aceess to go website in Chian

### ISSUE THREAD

**Issue by bitcometz** [docker/doodle#5]
Hi,
I run the command and got the error information:
**docker build -t bitcometz/cheers2019 .**

Error:
Sending build context to Docker daemon   12.8kB
Step 1/9 : FROM golang:1.11-alpine AS builder
 ---> 419986b2b50a
Step 2/9 : RUN apk add --no-cache git
 ---> Using cache
 ---> 2feb24c28c14
Step 3/9 : RUN go get github.com/pdevine/go-asciisprite
 ---> Running in 8317fc58cb96
package golang.org/x/text/encoding: unrecognized import path "golang.org/x/text/encoding" (https fetch: Get https://golang.org/x/text/encoding?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package golang.org/x/text/transform: unrecognized import path "golang.org/x/text/transform" (https fetch: Get https://golang.org/x/text/transform?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
The command '/bin/sh -c go get github.com/pdevine/go-asciisprite' returned a non-zero code: 1

Thanks

**Comment by pdevine** [comment]
hey @bitcometz what platform/version of docker are you using?  Also, can you reach https://golang.org directly?

**Comment by bitcometz** [comment]
hello,
I can visit https://golang.org/ with my chrome under the google helper's proxy web access.
I used the docker version : Docker version 18.09.2, build 6247962

I used the terminal of the Mac computer, 
ping golang.org
ping: cannot resolve golang.org: Unknown host


Is it my own network problem ? 

Thanks!

**Comment by pdevine** [comment]
@bitcometz unfortunately I think you need to modify the Dockerfile to make this work correctly with a proxy.  You could try something like:

`FROM golang:1.11-alpine AS builder
RUN apk add --no-cache git
RUN git config --global http.proxy http://proxy.mycompany:80
RUN http_proxy=proxy.mycompany:80 go get github.com/pdevine/go-asciisprite
WORKDIR /project
COPY cheers.go .
RUN CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' -o cheers cheers.go

FROM scratch
COPY --from=builder /project/cheers /cheers
ENTRYPOINT ["/cheers"]`

I'm not 100% sure of the syntax there, but hopefully that steers you in the correct direction.

**Comment by bitcometz** [comment]
Thanks for your help and I will try !!!

**Comment by heloook** [comment]
I encountered the same problem.

**Comment by sanbeichahegongheguo** [comment]
> Thanks for your help and I will try !!!

Did you resolve this problome?
I also meet this error.
