### ISSUE TITLE
compatible version for China user，because gfw ban golang.org

### ISSUE THREAD

**Issue by rexiyz** [docker/doodle#8]
https://github.com/rexiyz/doodle/tree/master

**Comment by pdevine** [comment]
It looks like the source is the same there?

**Comment by rexiyz** [comment]
the compatible version get golang/text from github，not golang.org.

**Comment by rexiyz** [comment]
> It looks like the source is the same there?

the compatible version get golang/text from github，not golang.org.

**Comment by pdevine** [comment]
I ended up vendoring in dependencies into the `go-asciisprite` library using the new golang module functionality, although I think it's a little unorthodox. I may still move these around, but for now it should be fine. I've tested docker build w/o a network connection and it seems to work fine, so I believe it should work now.

**Comment by pdevine** [comment]
@rexiyz do you want to try pulling the source and trying again?

**Comment by rexiyz** [comment]
> @rexiyz do you want to try pulling the source and trying again?

cool, it works without vpn too

**Comment by pdevine** [comment]
Awesome! Will close the issue again.
